### ISSUE TITLE
Doesn't seem to be working Chrome?

### ISSUE THREAD

**Issue by davidlionel** [gpiskas/Facebook_Delete_My_Timeline#2]
@Geo-Piskas 
Hi there. This is incredible work you have achieved, but the Chrome extension doesn't seem to be working. It "looks like" it is working (bar comes down, press launch, refresh, tells me "attempted to hide / delete x items"), but none of the posts in activity log are actually deleted. 

Do you have any plans to further development on this extension?

Thank you very much for your time. :)

**Comment by gpiskas** [comment]
Sorry, but Facebook does not like my addon and it changes a lot its layout, so I cannot keep up with the fast changes. When I have enough free time, I will do something about it.
